export type AntivenomListEntry = {
  name: string;
  district: string;
  state: "Kerala";
  sourceName: string;
  sourceUrl: string;
  aliases?: string[];
};

const SOURCE_NAME = "Digit Kerala antivenom list (2026)";
const SOURCE_URL = "https://digitkerala.com/anti-snake-venom-hospital-in-kerala/";

export const keralaAntivenomList: AntivenomListEntry[] = [
  {
    name: "Government Medical College, Trivandrum",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Medical College, Thiruvananthapuram"],
  },
  {
    name: "SAT Trivandrum",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["SAT Hospital, Thiruvananthapuram"],
  },
  {
    name: "General Hospital, Trivandrum",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["General Hospital, Thiruvananthapuram"],
  },
  {
    name: "General Hospital, Neyyattinkara",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "PRS Hospital, Killipalam",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "CSI Medical College, Karakonam",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Gokulam Medical College, Venjaramoodu",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "KIMS Hospital",
    district: "Thiruvananthapuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["KIMS Hospital, Trivandrum"],
  },
  {
    name: "District Hospital, Kollam",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Government District Hospital, Kollam", "Jilla Hospital, Kollam"],
  },
  {
    name: "Taluk Headquarters Hospital, Kottarakkara",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Punalur",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Sasthamcotta",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Karunagappally",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Medical College, Paripally",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Ideal Hospital, Karunagappally",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "St. Joseph's Mission Hospital, Anchal",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Upasana Hospital, Kollam",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Travancore Medicity, Kollam",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Travancore Medici, Kollam"],
  },
  {
    name: "Holy Cross Hospital, Kottiyam",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Azeezia Medical College Hospital",
    district: "Kollam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Pathanamthitta",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Adoor",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Thiruvalla",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Kozhencherry",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Ranni",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Mallapally",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Pushpagiri Medical College, Thiruvalla",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Holy Cross Hospital, Adoor",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Thiruvalla Medical Mission",
    district: "Pathanamthitta",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Medical College, Alappuzha",
    district: "Alappuzha",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Mavelikkara",
    district: "Alappuzha",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Cherthala",
    district: "Alappuzha",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Chengannur",
    district: "Alappuzha",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "KCM Hospital, Nooranad",
    district: "Alappuzha",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Medical College, Kottayam",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Institute of Child Health, Kottayam",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Kottayam",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Kanjirapally",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Community Health Center, Erumeli",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Vaikom",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Caritas Hospital",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Caritas Hospital, Kottayam"],
  },
  {
    name: "Bharat Hospital",
    district: "Kottayam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Bharat Hospital, Kottayam"],
  },
  {
    name: "Government Medical College, Cochin",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Government Medical College, Kochi"],
  },
  {
    name: "General Hospital, Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Colenchery Medical Mission Hospital",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Medical Mission Hospital, Kolenchery"],
  },
  {
    name: "Mar Baselios Hospital, Kothamangalam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Charlie's Hospital, Muvattupuzha",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Little Flower Hospital, Angamaly",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Medical Trust Hospital, Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Aster Medcity, Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Aster Medicine, Ernakulam"],
  },
  {
    name: "Amrita Medical College, Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Lake Shore Hospital, Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Lakeshore Hospital, Ernakulam"],
  },
  {
    name: "St. George Hospital, Vazhakkulam",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Paravur",
    district: "Ernakulam",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Medical College, Thrissur",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Jubilee Medical Mission, Thrissur",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Irinjalakuda Co-operative Hospital",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Malankara Hospital, Kunnamkulam",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Elite Hospital, Coorgancheri",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Amala Medical College, Thrissur",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Thrissur",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Wadakkanchery",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Kodungalloor",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Chalakkudy",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Taluk Headquarters Hospital, Chalakudy"],
  },
  {
    name: "Taluk Headquarters Hospital, Pudukkad",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Kunnamkulam",
    district: "Thrissur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Tribal Specialty Hospital, Kottathara",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Palawan Hospital",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Valluvanad Hospital, Ottapalam",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "PK Das Institute of Medical Science",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["PK Das Institute of Medical Sciences"],
  },
  {
    name: "Government District Hospital, Palakkad",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["District Hospital, Palakkad"],
  },
  {
    name: "Service Hospital, Pattambi",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Primary Health Center, Putur",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Primary Health Center, Puthur"],
  },
  {
    name: "Women's and Children's Hospital, Palakkad",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Womens and Childrens Hospital, Palakkad"],
  },
  {
    name: "Taluk Headquarters Hospital, Ottapalam",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Perinthalmanna",
    district: "Palakkad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["District Hospital, Perinthalmanna (listed under Palakkad)"],
  },
  {
    name: "Manjeri Medical College",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Government Medical College, Manjeri"],
  },
  {
    name: "Almas",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Almas Hospital"],
  },
  {
    name: "Kim Al-Shifa Hospital, Perinthalmanna",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["KIMS Al Shifa Hospital, Perinthalmanna"],
  },
  {
    name: "Maulana Hospital, Perinthalmanna",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Mission Hospital, Kotkal",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Alshifa Hospital, Perinthalmanna",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Al Shifa Hospital, Perinthalmanna"],
  },
  {
    name: "EMS Hospital, Perinthalmanna",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Perinthalmanna",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Tirur",
    district: "Malappuram",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Painavu",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Thodupuzha",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Nedukandam",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Peermede",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Hospital, Adimali",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Primary Health Center, Peruvantanam",
    district: "Idukki",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Mananthavady",
    district: "Wayanad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Headquarters Hospital, Bathery",
    district: "Wayanad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["District Hospital, Sulthan Bathery"],
  },
  {
    name: "General Hospital, Kalpetta",
    district: "Wayanad",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Government Medical College, Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Aster Mims Hospital, Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Baby Memorial Hospital",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Baby Memorial Hospital, Kozhikode"],
  },
  {
    name: "Asha Hospital, Vadakara",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Vadakara",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Taluk Headquarters Hospital, Koyilandy",
    district: "Kozhikode",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "Pariyaram Medical College",
    district: "Kannur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Government Medical College, Pariyaram"],
  },
  {
    name: "Co-operative Hospital, Thalassery",
    district: "Kannur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Cooperative Hospital, Thalassery"],
  },
  {
    name: "AKG Memorial Hospital",
    district: "Kannur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Thalassery",
    district: "Kannur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "District Hospital, Kannur",
    district: "Kannur",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
  },
  {
    name: "General Hospital, Kasaragod",
    district: "Kasaragod",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["General Hospital, Kasargod"],
  },
  {
    name: "District Hospital, Kanhangad",
    district: "Kasaragod",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["District Hospital, Kanahngad"],
  },
  {
    name: "Haridas Clinic, Neeleswaram",
    district: "Kasaragod",
    state: "Kerala",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    aliases: ["Haridas Clinic, Nileshwaram"],
  },
];
